name: dart.smtp
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  tiny_parser:
    path: /Users/kyorohiro/wdart/dart.pico_parser
#    git:
#      url: https://github.com/kyorohiro/dart.tiny_parser.git
#      ref: v0.4.2

dev_dependencies:
  test: ^1.0.0
